# Generated by Django 4.2.7 on 2024-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="名称")),
                ("zhonglei", models.CharField(max_length=512, verbose_name="种类")),
                ("caozuo", models.CharField(max_length=512, verbose_name="操作")),
            ],
        ),
        migrations.CreateModel(
            name="dingshi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("neirong", models.CharField(max_length=512, verbose_name="内容")),
                ("shijian", models.CharField(max_length=512, verbose_name="时间")),
                (
                    "wenben",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="文本"
                    ),
                ),
            ],
        ),
    ]
